spring.application.name=melishop
spring.datasource.url=jdbc:mysql://localhost:3306/melishopdb
spring.datasource.username=root
spring.datasource.password=root9090
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.data.jdbc.repositories.enabled=true
spring.data.jdbc.dialect=mysql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.tomcat.access-to-underlying-connection-allowed=true
spring.jpa.show-sql=true
